"""empty message

Revision ID: 008804b399d4
Revises: 29e4561ed21d
Create Date: 2020-05-03 15:52:16.701060

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '008804b399d4'
down_revision = '29e4561ed21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipient', sa.Column(
        'address_notes', sa.String(), nullable=True))
    op.add_column('recipient', sa.Column(
        'userdir_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'recipient', ['userdir_id'])
    op.drop_constraint('recipient_username_fkey',
                       'recipient', type_='foreignkey')
    op.create_foreign_key(None, 'recipient', 'userdirectory', [
                          'userdir_id'], ['id'])
    op.drop_column('recipient', 'payment_notes')
    op.drop_column('recipient', 'store')
    op.drop_column('recipient', 'dropoff_notes')
    op.drop_column('recipient', 'dropoff_day')
    op.add_column('transaction', sa.Column(
        'payment_notes', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column(
        'payment_type', sa.String(), nullable=True))

    op.create_unique_constraint(None, 'userdirectory', ['username'])
    op.add_column('volunteer', sa.Column(
        'userdir_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'volunteer', ['userdir_id'])
    op.drop_constraint('volunteer_username_fkey',
                       'volunteer', type_='foreignkey')
    op.create_foreign_key(None, 'volunteer', 'userdirectory', [
                          'userdir_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer', type_='foreignkey')
    op.create_foreign_key('volunteer_username_fkey', 'volunteer', 'userdirectory', [
                          'username'], ['username'])
    op.drop_constraint(None, 'volunteer', type_='unique')
    op.drop_column('volunteer', 'userdir_id')
    op.drop_constraint(None, 'userdirectory', type_='unique')

    op.drop_column('transaction', 'payment_type')
    op.drop_column('transaction', 'payment_notes')
    op.add_column('recipient', sa.Column(
        'dropoff_day', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipient', sa.Column('dropoff_notes',
                                         sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipient', sa.Column(
        'store', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipient', sa.Column('payment_notes',
                                         sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipient', type_='foreignkey')
    op.create_foreign_key('recipient_username_fkey', 'recipient', 'userdirectory', [
                          'username'], ['username'])
    op.drop_constraint(None, 'recipient', type_='unique')
    op.drop_column('recipient', 'userdir_id')
    op.drop_column('recipient', 'address_notes')
    # ### end Alembic commands ###
