"""empty message

Revision ID: 0d68ca348c67
Revises: 
Create Date: 2020-05-04 11:30:47.913129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d68ca348c67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('transaction', sa.Column('image_fname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'image_fname')
    op.drop_column('transaction', 'image')
    # ### end Alembic commands ###
