"""empty message

Revision ID: 29e4561ed21d
Revises: 
Create Date: 2020-05-03 15:29:34.841954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e4561ed21d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'userdirectory', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userdirectory', type_='unique')
    # ### end Alembic commands ###
