"""empty message

Revision ID: 49b843cb0339
Revises: d7a96cc7aa23
Create Date: 2020-07-07 15:00:14.728531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b843cb0339'
down_revision = 'd7a96cc7aa23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipient', sa.Column('buddy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipient', 'volunteer', ['buddy_id'], ['id'])
    op.drop_constraint('volunteer_buddy_id_fkey', 'volunteer', type_='foreignkey')
    op.drop_column('volunteer', 'buddy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('buddy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('volunteer_buddy_id_fkey', 'volunteer', 'recipient', ['buddy_id'], ['id'])
    op.drop_constraint(None, 'recipient', type_='foreignkey')
    op.drop_column('recipient', 'buddy_id')
    # ### end Alembic commands ###
