"""empty message

Revision ID: 53b0882689ce
Revises: ce698d9bb8ee
Create Date: 2020-04-23 12:14:13.882143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b0882689ce'
down_revision = 'ce698d9bb8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('booking_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_transaction_booking_date'), 'transaction', ['booking_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_booking_date'), table_name='transaction')
    op.drop_column('transaction', 'booking_date')
    # ### end Alembic commands ###
