"""empty message

Revision ID: 57e975087600
Revises: 
Create Date: 2020-04-28 22:52:11.978768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e975087600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipient', 'grocery_list')
    op.add_column('transaction', sa.Column('tip', sa.Float(), nullable=True))
    op.drop_column('transaction', 'modification_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('modification_count', sa.INTEGER(), nullable=True))
    op.drop_column('transaction', 'tip')
    op.add_column('recipient', sa.Column('grocery_list', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
