"""empty message

Revision ID: 77fbc0374fe6
Revises: ae2cb61b3305
Create Date: 2020-05-02 21:49:26.387280

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import CreateSequence, Sequence

# revision identifiers, used by Alembic.
revision = '77fbc0374fe6'
down_revision = 'ae2cb61b3305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('userdirectory_id_seq')))
    op.drop_constraint('recipient_email_key', 'recipient', type_='unique')
    op.add_column("userdirectory", "id", nullable=False, server_default=sa.text(
        "nextval('userdirectory_id_seq'::regclass)"))
    op.alter_column('userdirectory', 'username',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=True)
    op.drop_constraint('volunteer_email_key', 'volunteer', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('volunteer_email_key', 'volunteer', ['email'])
    op.alter_column('userdirectory', 'username',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=False)
    op.drop_column('userdirectory', 'id')
    op.create_unique_constraint('recipient_email_key', 'recipient', ['email'])
    # ### end Alembic commands ###
