"""empty message

Revision ID: 7d4508ab80f6
Revises: 268ebd9efe26
Create Date: 2020-06-30 12:30:11.263723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4508ab80f6'
down_revision = '268ebd9efe26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'image_fname')
    op.drop_column('transaction', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transaction', sa.Column('image_fname', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
