"""empty message

Revision ID: 93516d6a81fd
Revises: 268ebd9efe26
Create Date: 2020-05-14 15:40:10.923591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93516d6a81fd'
down_revision = '268ebd9efe26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipient', sa.Column('_username', sa.String(length=64), nullable=True))
    op.drop_constraint('recipient_username_key', 'recipient', type_='unique')
    op.create_unique_constraint(None, 'recipient', ['_username'])
    op.drop_column('recipient', 'username')
    op.create_foreign_key(None, 'transaction', 'recipient', ['recipient_id'], ['id'])
    op.add_column('volunteer', sa.Column('_username', sa.String(length=64), nullable=True))
    op.drop_constraint('volunteer_username_key', 'volunteer', type_='unique')
    op.create_unique_constraint(None, 'volunteer', ['_username'])
    op.drop_column('volunteer', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'volunteer', type_='unique')
    op.create_unique_constraint('volunteer_username_key', 'volunteer', ['username'])
    op.drop_column('volunteer', '_username')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.add_column('recipient', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipient', type_='unique')
    op.create_unique_constraint('recipient_username_key', 'recipient', ['username'])
    op.drop_column('recipient', '_username')
    # ### end Alembic commands ###
