"""empty message

Revision ID: 9b25c7e23a40
Revises: cecfc0765b26
Create Date: 2020-05-04 11:46:32.844989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b25c7e23a40'
down_revision = 'cecfc0765b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('transaction', 'image_fname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('image_fname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'image_url')
    # ### end Alembic commands ###
