"""empty message

Revision ID: 9e6b46beee67
Revises: 
Create Date: 2020-04-30 15:26:54.860953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6b46beee67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdirectory', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('userdirectory', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userdirectory', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('userdirectory', 'id')
    # ### end Alembic commands ###
