"""empty message

Revision ID: a916fa4f8df8
Revises: 7d4508ab80f6
Create Date: 2020-06-30 16:52:18.810062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a916fa4f8df8'
down_revision = '7d4508ab80f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('flexible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'flexible')
    # ### end Alembic commands ###
