"""empty message

Revision ID: b3d5b0a6b10c
Revises: 9b25c7e23a40
Create Date: 2020-05-04 12:18:43.940809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d5b0a6b10c'
down_revision = '9b25c7e23a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('image_fname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'image_fname')
    # ### end Alembic commands ###
