"""empty message

Revision ID: ce698d9bb8ee
Revises: d15af67b9229
Create Date: 2020-04-21 20:46:44.935936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce698d9bb8ee'
down_revision = 'd15af67b9229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('list', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'list')
    # ### end Alembic commands ###
